spring.application.name=Merch

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/merch
spring.datasource.username=postgres
spring.datasource.password=*****
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Flyway
spring.flyway.enabled=true

#JWT
jwt.private-key=classpath:certs/private.pem
jwt.public-key=classpath:certs./public.pem
jwt.access-token-expiration=60m
